var comm_url = "https://request.pushalert.co/";
var default_title = "";
var default_message = "";
var default_icon = "https://cdn.pushalert.co/img/pushalert-square-icon.png";
var default_url = "https://newsexporter.blogspot.com";
var last_updated = "1740578098";
var client_id = 57383;
var domain_id = 2;
var pa_subdomain = "https://newsexporter980.pushalert.co";
var appPublicKey = 'BMD68/jVucgKY9ki9bv8PgC8nmF+2X0rImz4BHYqK1FkbQH9R9c0n37Ho4xsQLRf4bTUqtmV7GLPplcOJgpxAOM=';
importScripts("https://cdn.pushalert.co/sw-external-payload.js?t="+last_updated);